#monitoring Deployment
{{ if .Values.monitoring.enabled -}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "bkci.names.fullname" . }}-monitoring
  labels: {{- include "bkci.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: microservice
    app.kubernetes.io/name: monitoring
spec:
  selector:
    matchLabels: {{- include "bkci.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: microservice
      app.kubernetes.io/name: monitoring
  {{- if not .Values.monitoring.autoscaling.enabled }}
  replicas: {{ .Values.monitoring.replicas }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "bkci.labels.standard" . | nindent 8 }}
        {{- if .Values.monitoring.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.monitoring.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: microservice
        app.kubernetes.io/name: monitoring
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccount }}
      {{- if .Values.monitoring.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.monitoring.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.monitoring.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.monitoring.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.monitoring.podAffinityPreset  "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.monitoring.podAntiAffinityPreset  "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.monitoring.nodeAffinityPreset.type "key" .Values.monitoring.nodeAffinityPreset.key "values" .Values.monitoring.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.monitoring.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.monitoring.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.monitoring.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.monitoring.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.monitoring.priorityClassName }}
      priorityClassName: {{ .Values.monitoring.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.monitoring.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.monitoring.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}        
      containers:
        - name: monitoring
          image: {{ include "bkci-backend.image" . }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          {{- if .Values.monitoring.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.monitoring.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.monitoring.resources }}
          resources: {{- toYaml .Values.monitoring.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MS_NAME
              value: monitoring
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: CHART_NAME
              value: {{ .Chart.Name }}
            - name: MULTI_CLUSTER
              value: {{ .Values.multiCluster.enabled | quote }}
            - name: DEFAULT_NAMESPACE
              value: {{ .Values.multiCluster.defaultNamespace }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.java.options }} -XX:InitialRAMPercentage={{ .Values.monitoring.jvm.heapPct }} -XX:MaxRAMPercentage={{ .Values.monitoring.jvm.heapPct }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          workingDir: /data/workspace/monitoring
          {{ if .Values.entrypoint.override }}
          command:
            - "/bin/bash"
            - "-c"
            - |
              cp /data/workspace/backend.bkci.sh .;
              /bin/bash backend.bkci.sh;
          {{ end }}
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: http
            initialDelaySeconds: {{ .Values.monitoring.jvm.initSecs }}
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: http
            initialDelaySeconds: {{ .Values.monitoring.jvm.initSecs }}
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          volumeMounts:
          - mountPath: /data/workspace/monitoring/jvm
            name: log-volume
            subPathExpr: bkci/jvm/$(POD_NAME)
          lifecycle:
              preStop:
                exec:
                  command:
                  - /bin/bash
                  - -c
                  - sleep 10 && ps -ef|grep java|grep -v grep|awk '{print $2}'|xargs kill -15
      volumes:
      - hostPath:
          path: /data
        name: log-volume
{{- end -}}
