spring:
  application:
    name: process${service-suffix}
    desc: DevOps Pipeline Service
    version: 4.0.0
    packageName: com.tencent.devops.process

# 并发配置
queueConcurrency:
  buildStart: 5
  stage: 5
  container: 5
  task: 10
  buildFinish: 5
  buildCancel: 5
  pipelineCreate: 5
  pipelineDelete: 2
  pipelineUpdate: 5
  timerTrigger: 5
  monitor: 1
  webhook: 1
  measure: 1
  market: 1
  containerStartup: 1
  heartBeat: 1
  timerChanger: 1

server:
  port: 21921
