# 该配置只能定义应用名， 其他配置信息请再devops-config修改
spring:
  application:
    name: dispatch-devcloud
    desc: DevOps Dispatch DevCloud Service
    version: 4.0.0
    packageName: com.tencent.devops.dispatch.devcloud
