#websocket Deployment
{{ if .Values.websocket.enabled -}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-websocket
  labels: {{- include "bkci.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: microservice
    app.kubernetes.io/name: websocket
spec:
  selector:
    matchLabels: {{- include "bkci.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: microservice
      app.kubernetes.io/name: websocket
  {{- if not .Values.websocket.autoscaling.enabled }}
  replicas: {{ .Values.websocket.replicas }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "bkci.labels.standard" . | nindent 8 }}
        {{- if .Values.websocket.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.websocket.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: microservice
        app.kubernetes.io/name: websocket
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccount }}
      {{- if .Values.websocket.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.websocket.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.websocket.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.websocket.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.websocket.podAffinityPreset  "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.websocket.podAntiAffinityPreset  "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.websocket.nodeAffinityPreset.type "key" .Values.websocket.nodeAffinityPreset.key "values" .Values.websocket.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.websocket.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.websocket.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.websocket.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.websocket.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.websocket.priorityClassName }}
      priorityClassName: {{ .Values.websocket.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.websocket.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.websocket.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}        
      containers:
        - name: websocket
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.backendImage "global" $) }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          {{- if .Values.websocket.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.websocket.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.websocket.resources }}
          resources: {{- toYaml .Values.websocket.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MS_NAME
              value: websocket
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE_PREFIX
              value: {{ include "common.names.fullname" . }}
          workingDir: /data/workspace/websocket
          {{ if .Values.entrypoint.override }}
          command:
            - "/bin/bash"
            - "-c"
            - |
              cp /data/workspace/backend.bkci.sh .;
              /bin/bash backend.bkci.sh;
          {{ end }}
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: http
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
{{- end -}}
