{{ if .Values.stream.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bkci.names.fullname" . }}-stream
  labels: {{- include "bkci.labels.standard" . | nindent 4 }}
    app.kubernetes.io/name: stream
    app.kubernetes.io/component: microservice
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector: {{- include "bkci.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: microservice
    app.kubernetes.io/name: stream
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
{{- end -}}
