# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__MYSQL_IP0__:__MYSQL_PORT__/devops_ci_environment?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __MYSQL_USER__
    password: __MYSQL_PASS__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21919
server:
  port: __BKCI_ENVIRONMENT_API_PORT__

environment:
  agent-package: __INSTALL_PATH__/__MODULE__/agent-package

influxdb:
  server: __INFLUXDB_SERVER__
  userName: __INFLUXDB_USERNAME__
  password: __INFLUXDB_PASSWORD__