# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__BK_CI_MYSQL_ADDR__/devops_ci_dispatch?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION%27
    username: __BK_CI_MYSQL_USER__
    password: __BK_CI_MYSQL_PASSWORD__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21922
server:
  port: __BK_CI_DISPATCH_API_PORT__

dispatch:
  workerFile: __BK_CI_HOME__/agent-package/jar/worker-agent.jar
  dockerFile: __BK_CI_HOME__/agent-package/jar/worker-agent.jar
  scripts: __BK_CI_HOME__/agent-package/script
  #defaultImageUrl: __BK_CI_DOCKER_IMAGE_PREFIX__/paas/bkdevops/centos7.2:v1
  #defaultImageName: centos7.2
  #dockerhostPort: __BK_CI_DOCKERHOST_API_PORT__
  jobQuota:
    systemAlertReceiver: 
    enable: false

codecc:
  path: __BK_CODECC_DATA_DIR__/tools
  covFile: build_dev.py
  toolFile: build_tool_dev.py
