# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__MYSQL_IP0__:__MYSQL_PORT__/devops_ci_plugin?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __MYSQL_USER__
    password: __MYSQL_PASS__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21925
server:
  port: __BKCI_PLUGIN_API_PORT__
