# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__MYSQL_IP0__:__MYSQL_PORT__/devops_ci_repository?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __MYSQL_USER__
    password: __MYSQL_PASS__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21916
server:
  port: __BKCI_REPOSITORY_API_PORT__

repository:
  git: # git 管理私有Token，一般不用，用于插件库分组
    devopsPrivateToken: __DEVOPS_GIT_PRIVATE_TOKEN__
    devopsGroupName: __DEVOPS_GIT_PLUGIN_GROUP_NAME__

scm:
  #svn open api url，如果不需要则放着即可
  svn:
    apiKey: __SVN_API_KEY__
    apiUrl: __SVN_URL__/rest
    webhookApiUrl: __SVN_URL__/rest/webhooks
    svnHookUrl: __HTTP_SCHEMA__://__BKCI_FQDN__:__BKCI_HTTPS_PORT__/ms/process/api/external/scm/codesvn/commit
  # git 仓库配置，如果不需要则放着即可
  git:
    url: http://__GIT_HOST__
    apiUrl: http://__GIT_HOST__/api/v3
    clientId: clientId
    clientSecret: Secret
    redirectUrl: http://__BKCI_FQDN__:__BKCI_HTTP_PORT__/console/codelib
    redirectAtomMarketUrl: http://__BKCI_FQDN__:__BKCI_HTTP_PORT__/console/store/atomList
    gitHookUrl: http://__BKCI_FQDN__:__BKCI_HTTP_PORT__/ms/process/api/external/scm/codegit/commit
    public:
      account: devops
      email: devops@devops.com
      secret: devops123
  external:
    #gitlab typo repository
    gitlab:
      apiUrl: __GITLAB_URL__/api/v4
      gitlabHookUrl: __HTTP_SCHEMA__://__BKCI_FQDN__:__BKCI_HTTPS_PORT__/ms/process/api/external/scm/gitlab/commit
    github:
      clientId: __GITHUB_CLIENT_ID__
      clientSecret: __GITHUB_CLIENT_SECRET__
      callbackUrl: https://__BKCI_FQDN__:__BKCI_HTTP_PORT__/external/api/external/github/oauth/callback
      redirectUrl: http://__BKCI_FQDN__:__BKCI_HTTP_PORT__/console/codelib
      appUrl: https://github.com/apps/__GITHUB_APP__
      signSecret: __GITHUB_SIGN_SECRET__