# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__BK_CI_MYSQL_ADDR__/devops_ci_repository?useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION%27
    username: __BK_CI_MYSQL_USER__
    password: __BK_CI_MYSQL_PASSWORD__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21916
server:
  port: __BK_CI_REPOSITORY_API_PORT__

repository:
  git: # git 管理私有Token，一般不用，用于插件库分组
    devopsPrivateToken: __BK_CI_REPOSITORY_GIT_PRIVATE_TOKEN__
    devopsGroupName: __BK_CI_REPOSITORY_GIT_PLUGIN_GROUP_NAME__

scm:
  #svn open api url，如果不需要则放着即可
  svn:
    apiKey: __BK_CI_REPOSITORY_SVN_API_KEY__
    apiUrl: __BK_CI_REPOSITORY_SVN_API_URL__  # 结尾一般为 /rest
    webhookApiUrl: __BK_CI_REPOSITORY_SVN_WEBHOOK_URL__  # 一般为 SVN_API_URL/webhooks
    svnHookUrl: __BK_CI_PUBLIC_URL__/ms/process/api/external/scm/codesvn/commit
  # git 仓库配置，如果不需要则放着即可
  git:
    url: __BK_CI_REPOSITORY_GIT_URL__
    apiUrl: __BK_CI_REPOSITORY_GIT_URL__/api/v3
    clientId: clientId
    clientSecret: Secret
    redirectUrl: __BK_CI_PUBLIC_URL__/console/codelib
    redirectAtomMarketUrl: __BK_CI_PUBLIC_URL__/console/store/atomList
    gitHookUrl: __BK_CI_PUBLIC_URL__/ms/process/api/external/scm/codegit/commit
    public:  # TODO 无用配置, 待清理.
      account: devops
      email: devops@devops.com
      secret: devops123
  external:
    #gitlab v4.
    gitlab:
      apiUrl: __BK_CI_REPOSITORY_GITLAB_URL__/api/v4
      gitlabHookUrl: __BK_CI_PUBLIC_URL__/ms/process/api/external/scm/gitlab/commit
    github:
      clientId: __BK_CI_REPOSITORY_GITHUB_CLIENT_ID__
      clientSecret: __BK_CI_REPOSITORY_GITHUB_CLIENT_SECRET__
      callbackUrl: __BK_CI_PUBLIC_URL__/__BK_CI_REPOSITORY_GITHUB_SERVER__/api/external/github/oauth/callback
      redirectUrl: __BK_CI_PUBLIC_URL__/console/codelib
      appUrl: https://github.com/apps/__BK_CI_REPOSITORY_GITHUB_APP__
      signSecret: __BK_CI_REPOSITORY_GITHUB_SIGN_SECRET__
      apiUrl: https://api.github.com
      serverUrl: https://github.com
      appId: __BK_CI_REPOSITORY_GITHUB_APPID__
      privateKey: __BK_CI_REPOSITORY_GITHUB_PRIVATEKEY__
      appName: __BK_CI_REPOSITORY_GITHUB_APPNAME__
    tGit:
      apiUrl: https://git.tencent.com/api/v3
      tGitHookUrl: __BK_CI_PUBLIC_URL__/ms/process/api/external/scm/codetgit/commit
    p4:
      p4HookUrl: __BK_CI_PUBLIC_URL__/ms/process/api/external/scm/p4/commit
tapd:
    clientId: __BK_CI_REPOSITORY_TAPD_CLIENT_ID__
    clientSecret: __BK_CI_REPOSITORY_TAPD_CLIENT_SECRET__
    redirectUrl: __BK_CI_PUBLIC_URL__/console/
    callbackUrl: __BK_CI_PUBLIC_URL__/repository/api/external/repo/tapd/callback
    serverUrl: __BK_CI_REPOSITORY_TAPD_SERVER_URL__
    apiUrl: __BK_CI_REPOSITORY_TAPD_API_URL__

aes:
  git: __BK_CI_REPOSITORY_AES_GIT__
