# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__MYSQL_IP0__:__MYSQL_PORT__/devops_ci_artifactory?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __MYSQL_USER__
    password: __MYSQL_PASS__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21918
server:
  port: __BKCI_STORE_API_PORT__

store:
  profileUrlPrefix: http://__PAAS_USER_AVATARS_URL__
  atomDetailBaseUrl: http://__BKCI_FQDN__:__BKCI_HTTP_PORT__/console/store/atomStore/detail/atom/
  templateDetailBaseUrl: http://__BKCI_FQDN__:__BKCI_HTTP_PORT__/console/store/atomStore/detail/template/

file:
  allowUploadFileTypes: jpg,png,gif,swf,txt,doc,docx,xls,xlsx,ppt,pptx,pdf,flv,rmvb,mp4,svg
  maxUploadFileSize: 52428800