# 服务配置文件模板
spring:
  datasource:
    dispatch:
      url: jdbc:mysql://__BK_CI_MYSQL_ADDR__/devops_ci_dispatch?useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
      username: __BK_CI_MYSQL_USER__
      password: __BK_CI_MYSQL_PASSWORD__
    dispatchKubernetes:
      url: jdbc:mysql://__BK_CI_MYSQL_ADDR__/devops_ci_dispatch_kubernetes?useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
      username: __BK_CI_MYSQL_USER__
      password: __BK_CI_MYSQL_PASSWORD__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21922
server:
  port: __BK_CI_DISPATCH_API_PORT__

dispatch:
  workerFile: __BK_CI_HOME__/agent-package/jar/worker-agent.jar
  dockerFile: __BK_CI_HOME__/agent-package/jar/worker-agent.jar
  scripts: __BK_CI_HOME__/agent-package/script
  agentLessRegistryUrl: __BK_CI_AGENTLESS_IMAGE_REGISTRY_URL__
  agentLessImageName: __BK_CI_AGENTLESS_IMAGE_NAME__
  agentLessRegistryUserName: __BK_CI_AGENTLESS_IMAGE_REGISTRY_USER__
  agentLessRegistryPassword: __BK_CI_AGENTLESS_IMAGE_REGISTRY_PASSWORD__
  jobQuota:
    systemAlertReceiver:
    enable: __BK_CI_DOCKER_JOB_QUOTA_ENABLE__
  # 默认的构建容器集群类型：VM, KUBERNETES, BCS
  defaultDockerRoutingType: __BK_CI_DOCKER_ROUTING_TYPE__

# kubernetes-dispatch集群配置
kubernetes:
  enable: __BK_CI_KUBERNETES_ENABLE__
  apiUrl: __BK_CI_KUBERNETES_HOST__
  token: __BK_CI_KUBERNETES_TOKEN__
  entrypoint: /data/devops/config/init.sh
  sleepEntrypoint: /data/devops/config/sleep.sh
  resources:
    builder:
      cpu: __BK_CI_KUBERNETES_CPU__
      memory: __BK_CI_KUBERNETES_MEMORY__
      disk: 100
    job:
      cpu: __BK_CI_KUBERNETES_CPU__
      memory: __BK_CI_KUBERNETES_MEMORY__
      disk: 100
  gateway:
    webConsoleProxy: __BK_CI_KUBERNETES_WEBCONSOLE_PROXY__
  privateBuilderTaint: __BK_CI_KUBERNETES_BUILDER_TAINT__

# 对接蓝鲸BCS容器调度集群需要用到的配置
bcs:
  enable: __BK_CI_BCS_ENABLE__
  apiUrl: __BK_CI_BCS_HOST__
  token: __BK_CI_BCS_TOKEN__
  entrypoint: /tools/bcs_init.sh
  sleepEntrypoint: /tools/sleep.sh
  resources:
    builder:
      cpu: __BK_CI_BCS_CPU__
      memory: __BK_CI_BCS_MEMORY__
      disk: 100
    job:
      cpu: __BK_CI_BCS_CPU__
      memory: __BK_CI_BCS_MEMORY__
      disk: 100

# 基础镜像源配置信息
registry:
  host: __BK_CI_DOCKER_REGISTRY_URL__
  userName: __BK_CI_DOCKER_REGISTRY_USER__
  password: __BK_CI_DOCKER_REGISTRY_PASSWORD__

gateway:
  url: __BK_CI_PRIVATE_URL__

thirdagent:
  workerErrorTemplate: __BK_CI_DISPATCH_THIRD_AGENT_WORKER_ERROR_TEMPLATE__
