# Image Service Template 服务配置文件模板
spring:
  datasource:
    dataSourceConfigs:
      - index: 0
        url: jdbc:mysql://__BK_CI_MYSQL_ADDR__/devops_ci_auth?useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
        username: __BK_CI_MYSQL_USER__
        password: __BK_CI_MYSQL_PASSWORD__

sharding:
  routing:
    cacheSize: 100000
  databaseShardingStrategy:
    shardingField: PROJECT_CODE
    algorithmClassName: "com.tencent.devops.auth.sharding.BkAuthDatabaseShardingAlgorithm"

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21936
server:
  port: __BK_CI_AUTH_API_PORT__

login:
  third:
    # 第三方登陆重定向页面地址
    url: __BK_CI_LOGIN_THIRD_CALLBACK_URL__
    # 第三方登陆重定向cookie作用域
    domain: __BK_CI_LOGIN_THIRD_COOKIE_DOMAIN__

itsm:
  # ITSM API地址
  url: __BK_CI_ITSM_APIGW_URL__
  callback:
    create:
      # 项目创建ITSM回调URL
      url: __BK_CI_PUBLIC_URL__/ms/auth/api/external/auth/itsm/create_callback
    update:
      # 项目更新ITSM回调URL
      url: __BK_CI_PUBLIC_URL__/ms/auth/api/external/auth/itsm/update_callback
codecc:
  openapi:
    token: __BK_CI_CODECC_OPENAPI_TOKEN__

# 是否开启创建蓝盾项目同步注册监控空间，并注册监控权限资源
monitor:
  register: __BK_CI_MONITOR_REGISTER__
  url: __BK_CI_MONITOR_URL__
  iamSystem: __BK_CI_MONITOR_IAM_SYSTEM__

# auth 服务加密，可修改
aes:
  auth: __BK_CI_AUTH_AES_AUTH_KEY__

sync:
  cron:
    enabled: __BK_CI_AUTH_SYNC_CRON_ENABLED__
