spring:
  application:
    name: store
    desc: DevOps Support Service
    version: 4.0
    packageName: com.tencent.devops.store
  cloud:
    consul:
      discovery:
        tags: local

logo:
  allowUploadLogoTypes: jpg,png,svg
  allowUploadLogoWidth: 200
  allowUploadLogoHeight: 200
  maxUploadLogoSize: 2097152

server:
  port: 21933