#prebuild configmap
{{ if .Values.configmap.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bkci.names.fullname" . }}-prebuild
  labels: {{- include "bkci.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: prebuild
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
    {{- include "bkci.prebuild.yaml" . | nindent 4 -}}
{{- end -}}
