#dispatch Deployment
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-dispatch
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: microservice
    app.kubernetes.io/name: dispatch
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: microservice
      app.kubernetes.io/name: dispatch
  replicas: {{ .Values.dispatch.replicas }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.dispatch.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.dispatch.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: microservice
        app.kubernetes.io/name: dispatch
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccount }}
      {{- if .Values.dispatch.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.dispatch.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.dispatch.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.dispatch.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.dispatch.podAffinityPreset "component" "microservice" "extraMatchLabels" (dict "app.kubernetes.io/name" "dispatch") "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.dispatch.podAntiAffinityPreset "component" "microservice" "extraMatchLabels" (dict "app.kubernetes.io/name" "dispatch") "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.dispatch.nodeAffinityPreset.type "key" .Values.dispatch.nodeAffinityPreset.key "values" .Values.dispatch.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.dispatch.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.dispatch.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.dispatch.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.dispatch.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.dispatch.priorityClassName }}
      priorityClassName: {{ .Values.dispatch.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.dispatch.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.dispatch.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}        
      containers:
        - name: dispatch
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.backendImage "global" $) }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          {{- if .Values.dispatch.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.dispatch.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.dispatch.resources }}
          resources: {{- toYaml .Values.dispatch.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MS_NAME
              value: dispatch
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE_PREFIX
              value: {{ include "common.names.fullname" . }}
            - name: JVM_XMS
              value: {{ .Values.dispatch.env.JVM_XMS }}
            - name: JVM_XMX
              value: {{ .Values.dispatch.env.JVM_XMX }}
          workingDir: /data/workspace/dispatch
          command:
            - "/bin/bash"
            - "-c"
            - |
              cp /data/workspace/backend.bkci.sh .;
              mkdir -p {{ .Values.config.bkCiHome }};
              ln -s /data/workspace/agent-package {{ .Values.config.bkCiHome }}/agent-package;
              /bin/bash backend.bkci.sh;
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: http
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1


