{{- if .Values.server.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-server-template
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  template.yaml: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        tbs/name: __crm_name__
      name: __crm_name__
      namespace: __crm_namespace__
    spec:
      replicas: __crm_instance__
      selector:
        matchLabels:
          tbs/name: __crm_name__
      template:
        metadata:
          labels:
            tbs/name: __crm_name__
          name: __crm_name__
          annotations:
            randhostport.webhook.bkbcs.tencent.com: "true"
            randcontainerport.randhostport.webhook.bkbcs.tencent.com: true
            ports.randhostport.webhook.bkbcs.tencent.com: "__crm_rand_port_names__"
        spec:
          __crm_host_network__
          containers:
          - name: __crm_name__
            image: __crm_image__
            ports: __crm_ports__
            env: __crm_env__
            - name: BK_DIST_WHITE_IP
              value: 0.0.0.0
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            volumeMounts: __crm_volume_mounts__
            resources:
              requests:
                memory: "__crm_request_mem__Mi"
                cpu: "__crm_request_cpu__m"
              limits:
                memory: "__crm_mem__Mi"
                cpu: "__crm_cpu__m"
          volumes: __crm_volumes__
          nodeSelector:
            __crm_platform_key__: __crm_platform__
            __crm_city_key__: __crm_city__
{{- end }}
