name: Agent CI

on:
  push:
    branches: [master]
    paths:
    - 'src/agent/**'
  pull_request:
    branches: [master, release-*]
    paths:
    - 'src/agent/**'
  workflow_dispatch:
  workflow_call:
    inputs:
      upload:
        required: true
        type: string

jobs:
  build:
    name: Build agent
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.6
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('src/agent/go.sum') }}
    - run: make BUILD_OUT_TAG=out clean all
      working-directory: src/agent/
    - uses: actions/upload-artifact@v4
      if: ${{ inputs.upload == 'true'  }}
      with:
        name: agent
        path: src/agent/bin/
