# This is a basic workflow to help you get started with Actions

name: Backend Booster Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    paths:
    - 'src/backend/booster/**'
  pull_request:
    branches: [master, release-*]
    paths:
    - 'src/backend/booster/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19.6
    - name: GO Mod
      working-directory: src/backend/booster
      run: |
        go mod download
        go get -u github.com/gobuffalo/packr/v2/packr2
        sed -i '8s/^/\/\//'  bk_dist/dashboard/pkg/dashboard/dashboard-packr.go
        go mod tidy
        sed -i '8s/^\/\///' bk_dist/dashboard/pkg/dashboard/dashboard-packr.go
    - name: GO Build
      working-directory: src/backend/booster
      run: make -j buildbooster dist
      env:
        GITTAG: ${{ github.ref }}
